import { ArrowLeft, ArrowRight, CalendarClock, Check, Info, LockKeyhole, Sparkles, Target, TrendingUp } from "lucide-react";
import { Link } from "wouter";
import { useMemo, useState } from "react";

const idr = (value: number) => new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(Math.max(0, Math.round(value)));
const groupedNumber = (value: number) => new Intl.NumberFormat("id-ID", { maximumFractionDigits: 0 }).format(Math.max(0, Math.round(value)));
const readLiquidNetworth = () => { try { const draft = localStorage.getItem("petakaya_networth_preview"); if (draft) { const parsed = JSON.parse(draft) as { assets?: Array<{ category: string; amount: number }> }; const liquid = (parsed.assets || []).filter(item => item.category === "Tabungan" || item.category === "Investasi").reduce((sum, item) => sum + Number(item.amount || 0), 0); if (liquid > 0) return liquid; } const raw = localStorage.getItem("petakaya_snapshot_preview"); const snapshots = raw ? JSON.parse(raw) : {}; const latest = snapshots["September 2026"] || Object.values(snapshots)[0] as { liquidAssets?: number } | undefined; return latest?.liquidAssets ?? 0; } catch { return 0; } };
const readCurrentAge = () => { try { const value = localStorage.getItem("petakaya_birth_date"); if (!value) return 29; const birth = new Date(value); const now = new Date(); let age = now.getFullYear() - birth.getFullYear(); if (now.getMonth() < birth.getMonth() || (now.getMonth() === birth.getMonth() && now.getDate() < birth.getDate())) age -= 1; return Math.max(18, Math.min(70, age)); } catch { return 29; } };

export default function Retirement() {
  const [age, setAge] = useState(readCurrentAge);
  const [retireAge, setRetireAge] = useState(55);
  const [monthlyNeed, setMonthlyNeed] = useState(12000000);
  const [liquidAssets] = useState(readLiquidNetworth);
  const years = Math.max(1, retireAge - age);
  const output = useMemo(() => {
    const inflation = 0.04;
    const returnRate = 0.07;
    const withdrawal = 0.04;
    const months = years * 12;
    const monthlyReturn = Math.pow(1 + returnRate, 1 / 12) - 1;
    const needAtRetirement = monthlyNeed * Math.pow(1 + inflation, years);
    const target = needAtRetirement * 12 / withdrawal;
    const futureCurrent = liquidAssets * Math.pow(1 + monthlyReturn, months);
    const requiredFuture = Math.max(0, target - futureCurrent);
    const monthlyWithdrawal = needAtRetirement;
    const projectedMonthlyWithdrawal = target * withdrawal / 12;
    return { needAtRetirement, target, futureCurrent, requiredFuture, monthlyWithdrawal, projectedMonthlyWithdrawal, gap: Math.max(0, target - liquidAssets), progress: Math.min(100, (liquidAssets / target) * 100), monthlyReturn };
  }, [age, retireAge, monthlyNeed, liquidAssets, years]);

  return <div className="min-h-[calc(100vh-74px)] bg-[#eef3eb] px-5 py-8 md:px-8 md:py-12"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><Link href="/" className="mb-5 flex w-fit items-center gap-2 text-xs font-bold text-[#718077] hover:text-[#1f2e2a]"><ArrowLeft size={15} /> Beranda</Link><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.17em] text-[#bc6c4c]"><CalendarClock size={14} /> Goal masa depan</div><h1 className="mt-3 font-display text-[45px] leading-none tracking-[-.035em] md:text-[58px]">Goal Pensiunmu.</h1><p className="mt-4 max-w-xl text-sm leading-6 text-[#718077]">Tujuan yang jelas membuat langkah lebih fokus dan nyata. Halaman ini membaca aset liquid terbaru dari Net Worth Tracking agar Goal Pensiun tetap terhubung dengan kondisi kamu.</p></div><Link href="/networth" className="flex w-fit items-center gap-2 rounded-full border border-[#d3dfd0] bg-white px-4 py-2.5 text-xs font-bold text-[#5f7164] hover:border-[#aebfae]"><TrendingUp size={15} /> Perbarui aset liquid</Link></div>
      <div className="mt-6 flex items-start gap-3 rounded-2xl border border-[#dce7d9] bg-white p-4 text-xs leading-5 text-[#718077]"><LockKeyhole size={15} className="mt-0.5 shrink-0 text-[#829b86]" /> {liquidAssets > 0 ? "Aset liquid tersinkron dari Net Worth Tracking. Perbarui snapshot jika ada perubahan." : "Belum ada data aset liquid. Setelah Premium aktif, angka ini mengikuti snapshot Tabungan dan Investasi milik pengguna."}</div>
      <div className="mt-6 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="rounded-[24px] border border-[#dbe5d9] bg-white p-6 md:p-8"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.17em] text-[#bc6c4c]"><Sparkles size={14} /> Asumsi personal</div><div className="mt-8 space-y-7"><SliderField label="Usia kamu saat ini" value={age} min={18} max={70} suffix="tahun" onChange={setAge} /><SliderField label="Target usia pensiun" value={retireAge} min={40} max={80} suffix="tahun" onChange={setRetireAge} /><MoneyField label="Kebutuhan hidup bulanan saat ini" value={monthlyNeed} onChange={setMonthlyNeed} required /><div className="grid gap-3 sm:grid-cols-3"><Assumption label="Inflasi" value="4% / tahun" /><Assumption label="Imbal hasil" value="7% / tahun" /><Assumption label="Penarikan" value="4% / tahun" /></div></div><div className="mt-8 flex items-start gap-2 rounded-xl bg-[#f4f7f1] p-3 text-[11px] leading-5 text-[#7d8b80]"><Info size={14} className="mt-0.5 shrink-0 text-[#8ba28d]" /> Aset yang dihitung hanya Tabungan dan Investasi/liquid. Rumah, kendaraan, dan aset non-liquid tidak masuk goal pensiun.</div></div>
        <div className="space-y-5"><div className="grid gap-5 md:grid-cols-2"><ComparisonCard title="Aset liquid saat ini" value={idr(liquidAssets)} tone="dark" caption="Diambil dari Net Worth" /><ComparisonCard title="Target dana pensiun" value={idr(output.target)} tone="clay" caption={`Kebutuhan ${idr(output.needAtRetirement)} / bulan saat usia ${retireAge}`} /></div><div className="rounded-[24px] bg-[#dfeee1] p-6 text-[#29483b] md:p-8"><div className="flex items-start justify-between"><div><p className="text-xs text-[#63816b]">Progress menuju target</p><p className="mt-3 font-display text-[42px] tracking-[-.035em] md:text-[52px]">{Math.round(output.progress)}%</p></div><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-white text-[#66816c]"><Target size={20} /></div></div><div className="mt-7 h-3 rounded-full bg-white/70"><div className="h-full rounded-full bg-[#7eb28b]" style={{ width: `${output.progress}%` }} /></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><div><p className="text-[11px] text-[#63816b]">Sisa target perlu dicapai</p><p className="mt-1 font-display text-2xl text-[#bc6c4c]">{idr(output.gap)}</p></div><div><p className="text-[11px] text-[#63816b]">Estimasi dana bulanan saat pensiun</p><p className="mt-1 font-display text-2xl text-[#29483b]">{idr(output.monthlyWithdrawal)}</p></div></div><p className="mt-6 text-xs leading-5 text-[#63816b]">Angka ini menggambarkan ruang hidup bulanan yang ingin disiapkan saat memasuki usia {retireAge}, bukan kewajiban setoran hari ini.</p></div><div className="rounded-[24px] border border-[#dbe5d9] bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-[#bc6c4c]">Ruang hidup masa depan</p><p className="mt-1 text-sm text-[#718077]">Target penarikan bulanan setelah pensiun</p></div><Sparkles size={18} className="text-[#b9cdb4]" /></div><div className="mt-5 rounded-2xl bg-[#fff4ec] p-5"><p className="text-xs text-[#9a6d5a]">Estimasi kebutuhan saat usia {retireAge}</p><p className="mt-2 font-display text-3xl text-[#bc6c4c]">{idr(output.monthlyWithdrawal)} / bulan</p></div><div className="mt-7 flex h-[130px] items-end gap-2">{[24, 30, 38, 48, 60, 73, 88, 100].map((h, i) => <div key={i} className="flex-1 rounded-t-md bg-[#c9ddc6]" style={{ height: `${h}%`, opacity: .42 + i * .07 }} />)}</div><div className="mt-3 flex justify-between text-[10px] font-semibold text-[#9aa79d]"><span>Sekarang</span><span>Usia {retireAge}</span></div></div></div></div>
      <div className="mt-6 flex flex-col gap-4 rounded-2xl border border-[#d8e3d5] bg-white p-5 md:flex-row md:items-center md:justify-between"><div><p className="text-sm font-bold">Target berubah, ruang hidup ikut berubah</p><p className="mt-1 text-xs text-[#849187]">Coba ubah usia pensiun atau kebutuhan bulanan untuk melihat estimasi penarikan saat pensiun.</p></div><Link href="/pricing" className="flex w-fit items-center gap-2 rounded-full bg-[#bc6c4c] px-5 py-3 text-xs font-bold text-white hover:bg-[#a95d40]">Buka akses Premium <ArrowRight size={14} /></Link></div><p className="mt-5 text-center text-[10px] leading-5 text-[#89968c]">Simulasi edukatif dengan asumsi return nominal 7%, inflasi 4%, dan penarikan 4% per tahun. Bukan jaminan hasil atau rekomendasi investasi.</p>
    </div></div>;
}

function SliderField({ label, value, min, max, suffix, onChange }: { label: string; value: number; min: number; max: number; suffix: string; onChange: (value: number) => void }) { return <div><div className="flex items-center justify-between"><label className="text-sm font-bold">{label}</label><span className="rounded-lg bg-[#edf3eb] px-2.5 py-1 text-xs font-bold text-[#637967]">{value} {suffix}</span></div><input type="range" min={min} max={max} value={value} onChange={e => onChange(Number(e.target.value))} className="mt-4 w-full accent-[#bc6c4c]" /><div className="mt-1 flex justify-between text-[10px] text-[#9aa79d]"><span>{min} {suffix}</span><span>{max} {suffix}</span></div></div>; }
function MoneyField({ label, value, onChange, required }: { label: string; value: number; onChange: (value: number) => void; required?: boolean }) { return <div><label className="text-sm font-bold">{label} {required && <span className="text-[#bc6c4c]">*</span>}</label><div className="relative mt-2"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-xs font-bold text-[#8a978e]">Rp</span><input required inputMode="numeric" value={groupedNumber(value)} onChange={e => onChange(Number(e.target.value.replace(/\D/g, "")) || 0)} className="w-full rounded-xl border border-[#dfe8dc] bg-[#fafcf9] py-3 pl-10 pr-3 text-sm font-bold outline-none focus:border-[#9fb59e]" /></div><p className="mt-1.5 text-[10px] text-[#9aa79d]">Wajib diisi agar target penarikan dapat dihitung. Gunakan titik sebagai pemisah ribuan.</p></div>; }
function Assumption({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-[#f0f5ed] p-3"><p className="text-[10px] text-[#849187]">{label}</p><p className="mt-1 text-xs font-bold text-[#637967]">{value}</p></div>; }
function ComparisonCard({ title, value, caption, tone }: { title: string; value: string; caption: string; tone: "dark" | "clay" }) { return <div className={`rounded-[24px] p-6 ${tone === "dark" ? "bg-[#1f2e2a] text-white" : "bg-[#f9e9e1] text-[#1f2e2a]"}`}><p className={`text-xs font-semibold ${tone === "dark" ? "text-[#b6c8b8]" : "text-[#a5654d]"}`}>{title}</p><p className="mt-3 font-display text-3xl">{value}</p><p className={`mt-2 text-[10px] ${tone === "dark" ? "text-[#91a894]" : "text-[#9c7869]"}`}>{caption}</p></div>; }
