from pathlib import Path
p=Path('/home/ubuntu/petakaya-financial-wellness/client/src/pages/Pricing.tsx')
s=p.read_text()
marker='</div></div></div>\n      {paymentOpen && <ManualPayment onClose={() => setPaymentOpen(false)} />}'
insert='''</div></div></div>
      <section className="mt-8 rounded-[28px] border border-[#d9c8e8] bg-[#ede4f7] p-7 md:p-10"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-start"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.17em] text-[#79559a]">Offer high-ticket · 1 on 1</p><h2 className="mt-4 font-display text-[42px] leading-[1.02] text-[#3e2d50] md:text-[54px]">Coaching Strategist</h2><p className="mt-5 text-sm leading-7 text-[#655875]">Pendampingan personal untuk membantu kamu membaca kondisi secara menyeluruh, menemukan prioritas yang paling penting, dan mengubah tujuan keluarga menjadi arah yang lebih jelas serta terukur.</p></div><div className="shrink-0 rounded-2xl bg-white/75 p-5 md:min-w-[220px] md:text-right"><p className="text-xs font-bold uppercase tracking-wider text-[#8a73a0]">Investasi layanan</p><p className="mt-2 font-display text-[38px] leading-none text-[#4b345d]">Rp10.000.000</p><p className="mt-2 text-xs text-[#806b91]">per program pendampingan</p></div></div><div className="mt-8 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-white/60 p-5"><p className="text-sm font-bold text-[#4b345d]">Yang ingin diperjelas</p><p className="mt-2 text-xs leading-6 text-[#766980]">Pola keputusan, kondisi Net Worth, arah Goal Pensiun, dan tujuan keluarga.</p></div><div className="rounded-2xl bg-white/60 p-5"><p className="text-sm font-bold text-[#4b345d]">Transformasi yang diharapkan</p><p className="mt-2 text-xs leading-6 text-[#766980]">Dari merasa berputar-putar menjadi memiliki prioritas dan target yang dapat ditinjau.</p></div><div className="rounded-2xl bg-white/60 p-5"><p className="text-sm font-bold text-[#4b345d]">Cara memulai</p><p className="mt-2 text-xs leading-6 text-[#766980]">Ceritakan kendala melalui WhatsApp. Admin akan membantu menjelaskan kecocokan dan langkah berikutnya.</p></div></div><div className="mt-8 flex flex-col gap-3 sm:flex-row sm:items-center"><a href={`https://wa.me/${waNumber}?text=${encodeURIComponent("Halo Admin Petakaya, saya ingin memahami Coaching Strategist dan menceritakan kondisi finansial saya.")}`} className="inline-flex items-center justify-center gap-2 rounded-full bg-[#79559a] px-6 py-3.5 text-sm font-bold text-white hover:bg-[#684888]">Ceritakan kondisi saya <MessageCircle size={16} /></a><p className="text-xs leading-5 text-[#766980]">Tidak ada janji hasil investasi. Sesi berfokus pada edukasi, refleksi, prioritas, dan langkah sesuai kondisi kamu.</p></div></section>
      {paymentOpen && <ManualPayment onClose={() => setPaymentOpen(false)} />}'''
if marker not in s: raise SystemExit('pricing insertion marker not found')
p.write_text(s.replace(marker,insert,1))
